GET http://localhost:5140/exercises/2
###
POST http://localhost:5140/exercises
Content-Type: application/json

{
    "name": "Deadlift",
    "reps": 8
}

###
PUT http://localhost:5140/exercises/2
 Content-Type: application/json

{
    "name": "Deadlift",
    "reps": 111
}

###
DELETE http://localhost:5140/exercises/1